### ISSUE TITLE
Does not work with hierarchical styles like Material Design convention.

### ISSUE THREAD

**Issue by romanr** [Mastersam07/figdart#8]
For whom is this plugin? Who is developing and organising styles in a flat one level list? And not using Material plugin to generate?  

Obviously Material 3 theme Figma styles do not work. 

<img width="1447" alt="image" src="https://github.com/Mastersam07/figdart/assets/329079/b74416ee-7457-47bb-8056-3d6a84fa43eb">

-------

Would expect it to at least merge style names resulting in `titleMedium`

**Comment by Mastersam07** [comment]
Thanks for filing an issue. 

This was designed to work with hierarchical styles like you stated: `titleMedium`, `displayLarge` etc

This has been marked as a `bug`.

**Comment by Mastersam07** [comment]
Hi @romanr 

This has been fixed in 37cb9b443448110e677fe5cf53da86db84085e95 and a new plugin version published.
